#!/bin/bash
docker build -t kill-ao-mat-beta .

containerName="kill-ao-mat-beta-$1"

docker stop $containerName
docker rm $containerName

docker create -it --name $containerName kill-ao-mat-beta
docker cp ./$1/config.json $containerName:/usr/src/app/config.json
docker start -i $containerName
