#!/bin/bash
docker build -t ao-killbot .

containerName="kill-ao-mat-$1"

docker stop $containerName
docker rm $containerName

docker create -it --name $containerName ao-killbot
docker cp ./$1/config.json $containerName:/usr/src/app/config.json
docker start -i $containerName
