#!/bin/bash
docker build -t kill-o-mat .

containerName="kill-o-mat-$1"

docker stop $containerName
docker rm $containerName

docker create -it --name $containerName kill-o-mat
docker cp ./$1/config.json $containerName:/usr/src/app/config.json
docker start $containerName
